#!/usr/bin/env python3
"""Assemble JLens_Ouro_Writer_Handoff_v2 (extracted dir + zip) from actual files. Access-restricted material is kept out.
Multi-gigabyte banks/states/weights stay in the SSD archive; the zip is not their backup."""
import json, shutil, hashlib, zipfile, sys, os
from pathlib import Path
RS = Path('/home/moloch/ouro_project/jacobian-lens/research'); X = RS / 'closeout_2026-09-11'; H = X / 'handoff' / 'JLens_Ouro_Writer_Handoff_v2'
C = RS / 'confirmation_2026-09-09'; V = RS / 'verification_2026-09-11'; R = RS / 'refit_round_2026-09-07'; F = RS / 'followup_2026-09-07'
A = C / 'cloud_leases/attempt_06/handoff/accepted/ouro_confirmation_20260911_fixed160_native1/ff7c0769b2b0dbe2e53b120daf7f0729434fe65e54c013288771f5052ffd4cef/results'
INP = Path('/tmp/claude-1000/-home-moloch-jacobian-lens/fcb94bb7-42d0-49fd-8993-7db96deb86a0/scratchpad/inputs')
if H.exists(): shutil.rmtree(H)
def cp(src, dst):
    dst = H / dst; dst.parent.mkdir(parents=True, exist_ok=True)
    if Path(src).is_dir(): shutil.copytree(src, dst, ignore=shutil.ignore_patterns('__pycache__', '*.pyc'))
    else: shutil.copyfile(src, dst)
# 01 reports (intact copies)
for p, d in [(F / 'REPORT.md', '01_reports/followup_2026-09-07/REPORT.md'), (F / 'CLAIMS.md', '01_reports/followup_2026-09-07/CLAIMS.md'), (F / 'BUGS_AND_CONCERNS.md', '01_reports/followup_2026-09-07/BUGS_AND_CONCERNS.md'), (F / 'RESEARCH_LOG.md', '01_reports/followup_2026-09-07/RESEARCH_LOG.md'), (F / 'REPRODUCE.md', '01_reports/followup_2026-09-07/REPRODUCE.md'), (F / 'literature.md', '01_reports/followup_2026-09-07/literature.md'), (F / 'REVIEW.md', '01_reports/followup_2026-09-07/REVIEW.md'), (F / 'results', '01_reports/followup_2026-09-07/results'), (F / 'audit/sensitivities.md', '01_reports/followup_2026-09-07/audit/sensitivities.md'), (F / 'audit/FOLLOWUP_VERIFICATION.md', '01_reports/followup_2026-09-07/audit/FOLLOWUP_VERIFICATION.md'), (F / 'probe/probe_audit.md', '01_reports/followup_2026-09-07/probe/probe_audit.md'), (F / 'probe/bounded_refit_results.json', '01_reports/followup_2026-09-07/probe/bounded_refit_results.json'),
             (R / 'REPORT.md', '01_reports/refit_round_2026-09-07/REPORT.md'), (R / 'CLAIMS.md', '01_reports/refit_round_2026-09-07/CLAIMS.md'), (R / 'RUN_LOG.md', '01_reports/refit_round_2026-09-07/RUN_LOG.md'), (R / 'audit/EVIDENCE.md', '01_reports/refit_round_2026-09-07/audit/EVIDENCE.md'), (R / 'audit/calibration_plan.json', '01_reports/refit_round_2026-09-07/audit/calibration_plan.json'), (R / 'audit/calibration_verification.json', '01_reports/refit_round_2026-09-07/audit/calibration_verification.json'), (R / 'analysis/CONTRACT.md', '01_reports/refit_round_2026-09-07/analysis/CONTRACT.md'), (R / 'analysis/HUGINN_COMPARISON_CONTRACT.md', '01_reports/refit_round_2026-09-07/analysis/HUGINN_COMPARISON_CONTRACT.md'), (R / 'analysis/ouro_run01_curves', '01_reports/refit_round_2026-09-07/analysis/ouro_run01_curves'), (R / 'BUDGET.md', '01_reports/refit_round_2026-09-07/BUDGET.md'), (R / 'COST_REVISION.md', '01_reports/refit_round_2026-09-07/COST_REVISION.md'), (R / 'GPU_AND_BUDGET_AFTER_OPTIMIZATION.md', '01_reports/refit_round_2026-09-07/GPU_AND_BUDGET_AFTER_OPTIMIZATION.md'), (R / 'deployment/ENVIRONMENT.md', '01_reports/refit_round_2026-09-07/deployment/ENVIRONMENT.md'), (R / 'monitoring/attempt_06/termination_incident', '01_reports/refit_round_2026-09-07/monitoring/attempt_06/termination_incident'), (R / 'cloud_leases/attempt_06/LEASE.json', '01_reports/refit_round_2026-09-07/cloud_leases/attempt_06/LEASE.json'),
             (C / 'README.md', '01_reports/confirmation_2026-09-09/README.md'), (C / 'REPORT.md', '01_reports/confirmation_2026-09-09/REPORT.md'), (C / 'CLAIMS.md', '01_reports/confirmation_2026-09-09/CLAIMS.md'), (C / 'PROSPECTIVE_PLAN.md', '01_reports/confirmation_2026-09-09/PROSPECTIVE_PLAN.md'), (C / 'FREEZE.json', '01_reports/confirmation_2026-09-09/FREEZE.json'), (C / 'RUN_LOG.md', '01_reports/confirmation_2026-09-09/RUN_LOG.md'), (C / 'corrections/precision_v1/FREEZE.json', '01_reports/confirmation_2026-09-09/corrections/precision_v1/FREEZE.json'), (C / 'corrections/precision_v1/IMPLEMENTATION_REVIEW.md', '01_reports/confirmation_2026-09-09/corrections/precision_v1/IMPLEMENTATION_REVIEW.md'), (C / 'corrections/native_check_v1/FREEZE.json', '01_reports/confirmation_2026-09-09/corrections/native_check_v1/FREEZE.json'), (C / 'benchmark/dependency_audit.md', '01_reports/confirmation_2026-09-09/benchmark/dependency_audit.md'), (C / 'benchmark/final_lexical_novelty.json', '01_reports/confirmation_2026-09-09/benchmark/final_lexical_novelty.json'), (C / 'reviews/benchmark_review.md', '01_reports/confirmation_2026-09-09/reviews/benchmark_review.md'), (C / 'reviews/precision_design_review.md', '01_reports/confirmation_2026-09-09/reviews/precision_design_review.md'), (C / 'reviews/attempt05_native_failure_forensics.md', '01_reports/confirmation_2026-09-09/reviews/attempt05_native_failure_forensics.md'), (C / 'reviews/diagnostic_native_logit_v1_reanalysis.md', '01_reports/confirmation_2026-09-09/reviews/diagnostic_native_logit_v1_reanalysis.md'), (C / 'artifacts/FINDINGS.md', '01_reports/confirmation_2026-09-09/artifacts/FINDINGS.md'), (C / 'artifacts/RECOVERY_LEDGER.json', '01_reports/confirmation_2026-09-09/artifacts/RECOVERY_LEDGER.json'), (C / 'artifacts/RETAINED_INPUTS_FINDINGS.md', '01_reports/confirmation_2026-09-09/artifacts/RETAINED_INPUTS_FINDINGS.md'), (C / 'resources/SPENDING_AND_SHUTDOWN.md', '01_reports/confirmation_2026-09-09/resources/SPENDING_AND_SHUTDOWN.md'), (C / 'PURGE_MANIFEST_2026-09-11.json', '01_reports/confirmation_2026-09-09/PURGE_MANIFEST_2026-09-11.json'), (R / 'PURGE_MANIFEST_2026-09-11.json', '01_reports/refit_round_2026-09-07/PURGE_MANIFEST_2026-09-11.json'), (Path('/home/moloch/ouro_project/artifacts/jlens/PURGE_MANIFEST_2026-09-11.json'), '01_reports/ouro_project_artifacts_jlens/PURGE_MANIFEST_2026-09-11.json'), (C / 'results/ouro_confirmation_20260911_fixed160_native1', '01_reports/confirmation_2026-09-09/results/ouro_confirmation_20260911_fixed160_native1'),
             (V / 'FINAL_VERIFICATION.md', '01_reports/verification_2026-09-11/FINAL_VERIFICATION.md'), (V / 'REPRODUCE.md', '01_reports/verification_2026-09-11/REPRODUCE.md'), (V / 'RUN_SPECIFICATION.json', '01_reports/verification_2026-09-11/RUN_SPECIFICATION.json'), (V / 'PROGRESS.md', '01_reports/verification_2026-09-11/PROGRESS.md'), (V / 'report', '01_reports/verification_2026-09-11/report'), (V / 'metrics/VERIFICATION_METRICS.json', '01_reports/verification_2026-09-11/metrics/VERIFICATION_METRICS.json'), (V / 'reviews', '01_reports/verification_2026-09-11/reviews'), (V / 'preservation/PRESERVATION_LEDGER.json', '01_reports/verification_2026-09-11/preservation/PRESERVATION_LEDGER.json'), (V / 'preservation/RESTORATION_CHECK.json', '01_reports/verification_2026-09-11/preservation/RESTORATION_CHECK.json'), (V / 'spending/SPENDING_AND_SHUTDOWN.md', '01_reports/verification_2026-09-11/spending/SPENDING_AND_SHUTDOWN.md'), (V / 'checker/README.md', '01_reports/verification_2026-09-11/checker/README.md'), (V / 'checker/endpoint_checker.py', '01_reports/verification_2026-09-11/checker/endpoint_checker.py'),
             (Path('/home/moloch/ouro_project/docs/jlens/B300_RESULTS_2026-09-05.md'), '01_reports/application_era/B300_RESULTS_2026-09-05.md'), (Path('/home/moloch/ouro_project/docs/jlens/METHODS.md'), '01_reports/application_era/METHODS.md')]:
    cp(p, d)
# 02 reviewer checks, 03 local exit, 04 methods, 05 data, 06 manuscript, 07 archive, 08 code
cp(X / 'reviewer_checks', '02_reviewer_checks'); cp(X / 'local_exit', '03_local_exit'); cp(X / 'methods', '04_methods')
for arm in ('raw', 'fit01', 'fit02', 'penultimate', 'sampled_sum', 'diagonal'): cp(A / f'readouts/{arm}.npz', f'05_data/accepted_payload/readouts/{arm}.npz')
for nm in ('population.json', 'benchmark.json', 'run_spec.json', 'provenance.json'): cp(A / nm, f'05_data/accepted_payload/{nm}')
cp(R / 'analysis/main_run01/paired_items.npz', '05_data/refit/main_run01/paired_items.npz'); cp(R / 'analysis/main_run01/main_cells.csv', '05_data/refit/main_run01/main_cells.csv'); cp(R / 'analysis/main_run01/per_fit_metrics.csv', '05_data/refit/main_run01/per_fit_metrics.csv'); cp(R / 'analysis/main_run01/main_metrics.csv', '05_data/refit/main_run01/main_metrics.csv'); cp(R / 'analysis/main_run01/report.json', '05_data/refit/main_run01/report.json'); cp(R / 'analysis/main_run01/examples.json', '05_data/refit/main_run01/examples.json')
cp(R / 'analysis/ouro_run01/control_metrics.csv', '05_data/refit/ouro_run01/control_metrics.csv'); cp(R / 'analysis/ouro_run01/control_comparisons_summary.json', '05_data/refit/ouro_run01/control_comparisons_summary.json'); cp(R / 'analysis/ouro_run01/report.json', '05_data/refit/ouro_run01/report.json')
cp(R / 'analysis/huginn_run01/metrics.csv', '05_data/refit/huginn_run01/metrics.csv'); cp(R / 'analysis/huginn_run01/cells.csv', '05_data/refit/huginn_run01/cells.csv'); cp(R / 'analysis/huginn_run01/report.json', '05_data/refit/huginn_run01/report.json'); cp(R / 'analysis/huginn_run01/examples.json', '05_data/refit/huginn_run01/examples.json')
for nm in ('arrays.npz', 'items.json', 'task_names.json', 'provenance.json', 'summary.json'): cp(Path('/home/moloch/ouro_project/artifacts/jlens/eval/b300_local_allexits_strict') / nm, f'05_data/application_era/b300_local_allexits_strict/{nm}')
for ut in range(4): cp(Path(f'/home/moloch/ouro_project/artifacts/jlens/lens/n100/exit{ut}.json'), f'05_data/application_era/lens_sidecars/exit{ut}.json')
cp(F / 'audit/dependence_clusters.csv', '05_data/followup/dependence_clusters.csv')
for nm in ('measurement.py', 'readouts.py', 'worker.py', 'prepare_population.py', 'artifacts.py', 'validate_outputs.py', 'bootstrap.py', 'freeze.py', 'launch.py', 'audit_novelty.py', 'self_test.py', 'download_model.py'): cp(C / f'corrections/native_check_v1/bundle/evaluation/{nm}', f'08_code/frozen_evaluation/{nm}')
cp(C / 'corrections/native_check_v1/bundle/analysis', '08_code/frozen_analysis'); cp(C / 'corrections/native_check_v1/bundle/ouro_project/src/ouro_jlens', '08_code/frozen_ouro_jlens'); cp(C / 'corrections/native_check_v1/bundle/repo/jlens', '08_code/frozen_jlens'); cp(C / 'corrections/native_check_v1/bundle/legacy', '08_code/frozen_legacy')
cp(R / 'deployment/run_refits.py', '08_code/refit_deployment/run_refits.py'); cp(R / 'deployment/run_controls.py', '08_code/refit_deployment/run_controls.py'); cp(R / 'deployment/control_estimators.py', '08_code/refit_deployment/control_estimators.py'); cp(R / 'deployment/combined_contract.json', '08_code/refit_deployment/combined_contract.json'); cp(R / 'fit_estimators.py', '08_code/refit_deployment/fit_estimators.py'); cp(R / 'deployment/environment.json', '08_code/refit_deployment/environment.json'); cp(C / 'benchmark/finalize_dependencies.py', '08_code/benchmark/finalize_dependencies.py'); cp(C / 'benchmark/assemble.py', '08_code/benchmark/assemble.py')
cp(X / 'manuscript/figure_data', '06_manuscript/figure_data'); cp(X / 'manuscript/figures', '06_manuscript/figures')
for nm in ('JLens_Ouro_Second_Draft.md', 'JLens_Ouro_Second_Draft.tex', 'JLens_Ouro_Second_Draft.pdf', 'CHANGELOG.md', 'header.tex'): cp(X / 'manuscript' / nm, f'06_manuscript/v2/{nm}')
for nm in ('JLens_Ouro_First_Draft.md', 'JLens_Ouro_First_Draft.tex', 'JLens_Ouro_First_Draft.pdf', 'JLens_Ouro_Editorial_Notes.md'): cp(INP / 'manuscript_inputs' / nm, f'06_manuscript/v1_original/{nm}')
cp(X / 'ledgers', '06_manuscript/ledgers')
for nm in ('ACCEPTANCE_RECEIPT.json', 'ARCHIVE_INDEX.md', 'README_ARCHIVE.md', 'SECRETS_FLAGGED.json', 'EXCLUSIONS.json', 'DEPENDENCIES.json', 'DEDUP_TABLE.json', 'RESTORATION_FROM_SSD.json', 'PURGE_ALLOWLIST_DRYRUN.json', 'PURGE_ALLOWLIST_DRYRUN.csv', 'PURGE_ALLOWLIST_DRYRUN.md', 'build_archive.py', 'restore_from_ssd.py', 'restore_isolated.sh', 'purge_allowlist.py'):
    if (X / 'archive' / nm).exists(): cp(X / 'archive' / nm, f'07_archive/{nm}')
cp(X / 'archive/ARCHIVE_MANIFEST.json', '07_archive/ARCHIVE_MANIFEST.json'); cp(X / 'PLAN.md', 'PLAN_closeout_2026-09-11.md'); cp(X / 'logs', 'logs')
cp(INP / 'JLens_Remaining_Work_Prompt.md', '00_task/JLens_Remaining_Work_Prompt.md'); cp(INP / 'START_HERE.md', '00_task/START_HERE.md'); cp(Path('/home/moloch/Downloads/JLens_Reviewer_Closeout_Addendum.md'), '00_task/JLens_Reviewer_Closeout_Addendum.md')
shutil.copyfile(X / 'handoff/README_FIRST.md', H / 'README_FIRST.md'); shutil.copyfile(X / 'handoff/verify_handoff.py', H / 'verify_handoff.py')
# manifest + zip
entries = []
for p in sorted(H.rglob('*')):
    if p.is_file(): entries.append({'path': p.relative_to(H).as_posix(), 'bytes': p.stat().st_size, 'sha256': hashlib.sha256(p.read_bytes()).hexdigest()})
(H / 'HANDOFF_MANIFEST.json').write_text(json.dumps({'schema': 'writer_handoff_manifest.v2', 'files': len(entries), 'bytes': sum(e['bytes'] for e in entries), 'entries': entries}, indent=1))
zp = X / 'handoff/JLens_Ouro_Writer_Handoff_v2.zip'
if zp.exists(): zp.unlink()
with zipfile.ZipFile(zp, 'w', zipfile.ZIP_DEFLATED, compresslevel=6) as z:
    for p in sorted(H.rglob('*')):
        if p.is_file(): z.write(p, ('JLens_Ouro_Writer_Handoff_v2/' + p.relative_to(H).as_posix()))
print(json.dumps({'files': len(entries) + 1, 'bytes_uncompressed': sum(e['bytes'] for e in entries), 'zip_bytes': zp.stat().st_size, 'zip_sha256': hashlib.sha256(zp.read_bytes()).hexdigest()}))
